### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by masterwok** [RedApparat/Fotoapparat#310]
#### Stack Trace

```
    Process: com.masterwok.simplebarcodescannerfree, PID: 30406
    java.util.ConcurrentModificationException
        at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
        at java.util.LinkedList$ListItr.next(LinkedList.java:888)
        at kotlin.collections.CollectionsKt__MutableCollectionsKt.filterInPlace$CollectionsKt__MutableCollectionsKt(MutableCollections.kt:164)
        at kotlin.collections.CollectionsKt__MutableCollectionsKt.filterInPlace$CollectionsKt__MutableCollectionsKt(MutableCollections.kt:184)
        at kotlin.collections.CollectionsKt__MutableCollectionsKt.removeAll(MutableCollections.kt:175)
        at io.fotoapparat.concurrent.CameraExecutor.cleanUpCancelledTasks(CameraExecutor.kt:39)
        at io.fotoapparat.concurrent.CameraExecutor.execute(CameraExecutor.kt:33)
        at io.fotoapparat.routine.orientation.StartOrientationRoutineKt$startOrientationMonitoring$1.invoke(StartOrientationRoutine.kt:15)
        at io.fotoapparat.routine.orientation.StartOrientationRoutineKt$startOrientationMonitoring$1.invoke(Unknown Source:2)
        at io.fotoapparat.hardware.orientation.OrientationSensor$onOrientationChanged$1.invoke(OrientationSensor.kt:27)
        at io.fotoapparat.hardware.orientation.OrientationSensor$onOrientationChanged$1.invoke(OrientationSensor.kt:11)
        at io.fotoapparat.hardware.orientation.RotationListener.onOrientationChanged(RotationListener.kt:18)
        at android.view.OrientationEventListener$SensorEventListenerImpl.onSensorChanged(OrientationEventListener.java:143)
        at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:889)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

#### What are you trying to achieve or the steps to reproduce?

Very difficult to reproduce, crash has only occurred once over the course of many days of development.

```kotlin
    val barcodeScanObservable: Observable<BarcodeScanResult> = Observable
            .interval(CameraInterval, TimeUnit.MILLISECONDS)
            .takeWhile { cameraIsReady }
            .flatMapSingle { takePicture() }
            .flatMapSingle { bitmapPhoto -> detectBarcodes(bitmapPhoto.bitmap) }

    private fun takePicture() = fotoapparat!!
            .takePicture()
            .toBitmap()
            .toSingle()
```

#### How did you initialize FA?

```kotlin
    private fun configureCamera(): Fotoapparat = Fotoapparat
            .with(requireContext())
            .into(cameraView)
            .focusMode { FocusMode.ContinuousFocusPicture }
            .flash { Flash.Torch }
            .lensPosition { LensPosition.Back }
            .photoResolution { Resolution(PhotoResolutionWidth, PhotoResolutionHeight) }
            .build()
            .apply {
                start()
            }
```

#### What was the result you received?

Crash

#### What did you expect?

No crash

#### Context:

* *FA version*: 2.4.0
* *Devices/APIs affected*: One Plus 5
* *any other relevant information*: n/a

**Comment by khukuh123** [comment]
Is there any fix to this issue cause the state is completed @masterwok ?

**Comment by masterwok** [comment]
@khukuh123 unfortunately, I created this issue so long ago when working with an older project I'm having trouble remembering. I _think_ I ended up ditching the use of Observable based on how the file ended up. The following snippet is from a stale project if that is any help:

```kotlin
package com.masterwok.simplebarcodescanner.fragments

import android.Manifest
import android.app.Dialog
import android.content.DialogInterface
import android.content.pm.PackageManager
import android.os.Bundle
import android.support.v4.app.DialogFragment
import android.support.v7.app.AlertDialog
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import com.masterwok.simplebarcodescanner.R
import com.masterwok.simplebarcodescanner.dagger.injectors.InjectableFragment
import com.masterwok.simplebarcodescanner.extensions.hasPermission
import io.fotoapparat.Fotoapparat
import io.fotoapparat.characteristic.LensPosition
import io.fotoapparat.parameter.Flash
import io.fotoapparat.parameter.FocusMode
import kotlinx.android.synthetic.main.fragment_camera.*

private const val RequestCameraPermissionCode = 666

class CameraFragment : InjectableFragment() {

    companion object {
        const val Tag = "Tag.CameraFragment"

        @JvmStatic
        fun createInstance() = CameraFragment().apply {
        }
    }

    init {
    }

    override fun onCreateView(
            inflater: LayoutInflater
            , container: ViewGroup?,
            savedInstanceState: Bundle?
    ): View? = inflater.inflate(
            R.layout.fragment_camera
            , container
            , false
    )

    private var fotoApparat: Fotoapparat? = null

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        subscribeToViewComponents()
    }

    private fun subscribeToViewComponents() {
        buttonTakePicture.setOnClickListener {
            takePicture()
        }
    }

    private fun takePicture() {
        fotoApparat
                ?.takePicture()
                ?.toBitmap()
                ?.whenAvailable { bitmapPhoto ->
                    val bitmap = bitmapPhoto?.bitmap

                    val x = 1
                }
    }

    override fun onResume() {
        super.onResume()

        if (!requireActivity().hasPermission(Manifest.permission.CAMERA)) {
            requestCameraPermission()
            return
        }

        fotoApparat = Fotoapparat
                .with(requireContext())
                .into(cameraView)
                .focusMode { FocusMode.ContinuousFocusPicture }
                .flash { Flash.Torch }
                .lensPosition { LensPosition.Back }
                .build()
                .apply {
                    start()
                }
    }

    override fun onPause() {
        fotoApparat?.stop()

        super.onPause()
    }

    private fun requestCameraPermission() {
        if (shouldShowRequestPermissionRationale(Manifest.permission.CAMERA)) {
            ConfirmationDialog().show(childFragmentManager, ConfirmationDialog.Tag)
            return
        }

        requestPermissions(
                arrayOf(Manifest.permission.CAMERA)
                , RequestCameraPermissionCode
        )
    }

    override fun onRequestPermissionsResult(
            requestCode: Int
            , permissions: Array<out String>
            , grantResults: IntArray
    ) {
        if (requestCode != RequestCameraPermissionCode) {
            super.onRequestPermissionsResult(
                    requestCode
                    , permissions
                    , grantResults
            )

            return
        }

        if (grantResults.size == 1 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
            return
        }

        // TODO: Show error dialog
    }

    internal class ConfirmationDialog : DialogFragment() {

        companion object {
            const val Tag = "Tag.ConfirmationDialog"
        }

        override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
            return AlertDialog.Builder(requireActivity())
                    .setMessage(R.string.permission_request_camera)
                    .setPositiveButton(android.R.string.ok) { _, _ ->
                        parentFragment!!.requestPermissions(
                                arrayOf(Manifest.permission.CAMERA),
                                RequestCameraPermissionCode
                        )
                    }
                    .create()

        }

    }

}
```
