### ISSUE TITLE
Kotlin 1.4 update breaks the library's critical functionality

### ISSUE THREAD

**Issue by miloszkleszczewski** [RedApparat/Fotoapparat#407]
With Kotlin's 1.4 update the Fotoapparat's `build()` function crashes with error: 

```
2020-08-24 10:57:08.883 7440-7440  E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com., PID: 7440
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/coroutines/experimental/CoroutineContext$Element;
        at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:55)
        at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:48)
        at io.fotoapparat.FotoapparatBuilder.buildInternal(FotoapparatBuilder.kt:191)
        at io.fotoapparat.FotoapparatBuilder.build(FotoapparatBuilder.kt:180)

```
Example code that should allow to reproduce: 

```
    private Fotoapparat createCamera() {
        return Fotoapparat
                .with(getContext())
                .into(cameraView)
                .previewScaleType(ScaleType.CenterCrop)
                .lensPosition(back())
                .build();
    }
```

**Comment by AndyAls** [comment]
I have the same problem. Have you solved this problem

**Comment by miloszkleszczewski** [comment]
@AndyAls I'm positive it's not possible to resolve it without modifying the library itself

**Comment by WhiteYaksha** [comment]
Same issue here

**Comment by miloszkleszczewski** [comment]
Version 2.7.0 works correctly
