### ISSUE TITLE
With Kotlin's 1.4+ update the Fotoapparat's build() function crashes with error:

### ISSUE THREAD

**Issue by AndyAls** [RedApparat/Fotoapparat#408]

**Comment by AndyAls** [comment]
```java 
2020-08-24 10:57:08.883 7440-7440  E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com., PID: 7440
    java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/coroutines/experimental/CoroutineContext$Element;
        at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:55)
        at io.fotoapparat.Fotoapparat.<init>(Fotoapparat.kt:48)
        at io.fotoapparat.FotoapparatBuilder.buildInternal(FotoapparatBuilder.kt:191)
        at io.fotoapparat.FotoapparatBuilder.build(FotoapparatBuilder.kt:180)
```

**Comment by WhiteYaksha** [comment]
I have exactly the same error

**Comment by AndyAls** [comment]
I upgraded to 2.7.0 and the problem is solved
